// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxYWRSQ6e5zi5ZoxK_Y1-alBlOAHEhxgA',
    appId: '1:468451981420:web:ba50918dc8064249af0049',
    messagingSenderId: '468451981420',
    projectId: 'hotel-management-flutter',
    authDomain: 'hotel-management-flutter.firebaseapp.com',
    storageBucket: 'hotel-management-flutter.appspot.com',
    measurementId: 'G-WJRLMYS7F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDwdO6VTXjseXm3x2ii7sXMOQCZRQY6jc',
    appId: '1:468451981420:android:8be4292ea06e4fdeaf0049',
    messagingSenderId: '468451981420',
    projectId: 'hotel-management-flutter',
    storageBucket: 'hotel-management-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsFrfTv4GnjuqmOiMj9CPPcN3ftGa-qGc',
    appId: '1:468451981420:ios:4b9438935ebe06a9af0049',
    messagingSenderId: '468451981420',
    projectId: 'hotel-management-flutter',
    storageBucket: 'hotel-management-flutter.appspot.com',
    iosClientId: '468451981420-37oo8cun7r21b1ip4qt7kmbqg3fb5ji6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
